create table postgres.roles
(
    id   int8 generated by default as identity,
    name varchar(20),
    primary key (id)
);
create table postgres.user_roles
(
    user_id int8 not null,
    role_id int8 not null,
    primary key (user_id, role_id)
);
create table postgres.users
(
    id        int8 generated by default as identity,
    email     varchar(50),
    firstname varchar(50),
    gender    varchar(20),
    status    int4,
    lastname  varchar(50),
    password  varchar(120),
    phone     varchar(50),
    username  varchar(20),
    primary key (id)
);

alter table if exists postgres.users drop constraint if exists UKr43af9ap4edm43mmtq01oddj6;
alter table if exists postgres.users add constraint UKr43af9ap4edm43mmtq01oddj6 unique (username);
alter table if exists postgres.users drop constraint if exists UK6dotkott2kjsp8vw4d0m25fb7;
alter table if exists postgres.users add constraint UK6dotkott2kjsp8vw4d0m25fb7 unique (email);
alter table if exists postgres.user_roles add constraint FKh8ciramu9cc9q3qcqiv4ue8a6 foreign key (role_id) references postgres.roles;
alter table if exists postgres.user_roles add constraint FKhfh9dx7w3ubf1co1vdev94g3f foreign key (user_id) references postgres.users;